---
- name: Launch k8s nodes
  hosts: localhost
  pre_tasks:
    - name: Set variables
      set_fact:
        name: "{{ lookup('env','NAME') | default('k8s', true) }}"
        state: "{{ lookup('env','STATE') | default('present', true) }}"
        node_count: "{{ lookup('env', 'NODE_COUNT') | default(3, true) }}"
  roles:
    - { role: openstack-security-groups, when: state == 'present' }
    - openstack-master
    - openstack-nodes
    - openstack-security-groups # HACK: needs to be called after instance creation when state==absent

- name: Node preparation
  hosts: all
  pre_tasks:
    - name: Set variables
      set_fact:
        name: "{{ lookup('env','NAME') | default('k8s', true) }}"
        state: "{{ lookup('env','STATE') | default('present', true) }}"
  tags:
    - bootstrap
  gather_facts: false
  roles:
    - common
